const PRODUCTS = [
  { id: 'oval-tray-bowl', name: 'Oval Tray & Bowl Set', price: 58, img: 'assets/gallery/1.png', category: 'Trays', alt: 'Plum and coral oval trays with matching round bowls', description: 'A pair of hand-carved oval trays in plum and coral glazes, each paired with a matching round bowl. Pressed texture runs through every piece, so no two sets glaze exactly alike.', size: 'Trays 10" x 6", bowls 5" diameter' },
  { id: 'carved-geo-plate', name: 'Carved Geometric Plate', price: 42, img: 'assets/gallery/8.jpeg', category: 'Plates', alt: 'Carved blue geometric dinner plate with wooden servers', description: 'A deep blue dinner plate carved with an intricate geometric pattern before glazing. Sized for a full meal and sturdy enough for everyday use.', size: '10" diameter' },
  { id: 'hexagon-plate-pair', name: 'Hexagon Plate Pair', price: 36, img: 'assets/gallery/14.png', category: 'Trinket Dishes', alt: 'Pair of red hexagonal trinket plates', description: 'Two small hexagonal dishes in a rich red glaze, perfect for rings, snacks, or anything that deserves a little ceremony on the way to the table.', size: '4" across, each' },
  { id: 'carved-oval-tray', name: 'Carved Oval Tray Set', price: 52, img: 'assets/gallery/15.png', category: 'Trays', alt: 'Pair of red carved oval trays with matching dip bowls', description: 'Carved oval serving trays in a warm red glaze, each set with a matching dip bowl tucked into the curve. Built for snacks, sauces, or small bites.', size: 'Trays 9" x 5", dip bowls 3" diameter' },
  { id: 'feather-bowl', name: 'Feather-Carved Serving Bowl', price: 64, img: 'assets/gallery/7.png', category: 'Bowls', alt: 'Carved blue feather-pattern bowl with wooden servers', description: 'A wide serving bowl carved with a feather-like pattern and finished in a deep blue glaze. Generously sized for salads, fruit, or a centerpiece spread.', size: '11" diameter x 3" deep' },
  { id: 'heart-trinket-trio', name: 'Heart Trinket Dish Trio', price: 34, img: 'assets/gallery/5.png', category: 'Trinket Dishes', alt: 'Three red heart-shaped trinket dishes in varying sizes', description: 'Three heart-shaped trinket dishes in graduated sizes, glazed in shades of red. Nest them together or scatter them across a shelf.', size: '3", 4", and 5" wide' },
  { id: 'palm-wave-plates', name: 'Palm Wave Plate Trio', price: 66, img: 'assets/gallery/10.png', category: 'Plates', alt: 'Three round plates with carved palm tree and wave pattern', description: 'A set of three round plates carved with a palm tree and wave motif, each glazed in a different tone from navy to green. Sold as a trio.', size: '8" diameter, each', imgStyle: 'position:absolute; top:50%; left:50%; width:145%; height:145%; object-fit:cover; transform:translate(-50%, -38%);' },
  { id: 'scalloped-leaf-plates', name: 'Scalloped Leaf Plate Pair', price: 48, img: 'assets/gallery/26.png', category: 'Plates', alt: 'Pair of scalloped leaf-pattern plates in orange and yellow', description: 'A pair of scalloped-edge plates carved with a leaf pattern, glazed in warm orange and yellow tones. Each plate is finished by hand, so edges and color vary slightly piece to piece.', size: '7" diameter, each' }
];
